[TSS]
TURRETS = [
  'GANTZO3THWWGYTL6KOAWGEUI6ICY3QAQJOYGE67W2VHW4BU7TOMTT7JR', # self
  'GB4OYM7TQTJSROWXHOJLKAX2IJ2QN4I6S6GCJH4MGWVTAO5Q5DPNADXX', # sdf-ecosystem
  'GAMGW7ZESFF2KVGL7EMBBIAXTFAOF3MNI2JBWSPLTGMAKOSVLHDNZMA2', # EverLife.AI
  'GAATC6A7OOY7P36FTDFEHKHG7OS72A3NTSGM4RA6HJ5GKHUOEVRWGM76', # Script3
  'GARBNUK4IZDGKDJTIEWAL6FTY3UDRSRV275X4H5JS2PGCKTZZ3NDYU5U', # Litemint
  'GDZACR7XAJWU3JLJ5TVDOLCVB5DCIY2K7PHDR7ODGCEQTNVENOPHLCF7', # Atemosta
  'GATCMFLSJYFQ3XVNMHXKWHVUYKGQ4FDRD6U7VXSDEIUDI7MVTK2SON5Q', # Ralphilius
  'GBLBOLGDUMO4ZGZ2W3G3G7COJPEBY5IFLEH5L77JRLV45LR2NPFD4BHM', # Q30
  'GCXI7CCUXY5NLWHXXAVK6PJKSKAM4R3WX266JKUSYFFRVDYSC7AQAMIM', # Lumensspace
  'GBT6R6IYIFYW5S5FDAIEX7WY2AS7ATHVRJAQS4PWXQCPJFQG55OSX76M', # Jesmarcs
  'GD5LGDET3SX7P4RZR2YPGAQARYKZSZSSPJK4OXVKNDAV2LA6NRJ5DJEQ', # Mozart
  'GB52GDQ52PIVAN275DRLHNYQ2CTE2B6FY7G5O3CCBAHWML7RMHGDXVB2', # Elliotfriend
  'GA6MDX3VHYROMN3PVJDG6FRP2B5U5XG3B7PLBHF3DYADPEUYO2R7EH2O', # Yarvis
]