name = "tss-wrangler"
type = "javascript"
usage_model = "bundled"
webpack_config = "webpack.config.js"
account_id = "106284cf75e1995191ec006d2173e149"
workers_dev = true

kv_namespaces = [
   { binding = "META", id = "cbc57c2acdef6590bfe14d1cb0905d9710a63e5a8cb94c9d9072aade8a976c49" },
   { binding = "TX_FUNCTIONS", id = "1a2b9293d39b4a8398e002286428f1c3" },
   { binding = "TX_FEES", id = "cdef6590bfe14d1cb0905d9710a63e5a" },
]
vars = { STELLAR_NETWORK = "TESTNET", HORIZON_URL = "https://horizon-testnet.stellar.org", TURRET_ADDRESS = "GANTZO3THWWGYTL6KOAWGEUI6ICY3QAQJOYGE67W2VHW4BU7TOMTT7JR", TURRET_RUN_URL = "https://qf8cg180qg.execute-api.us-east-1.amazonaws.com", TX_FUNCTION_FEE_DAYS_TTL = 180, XLM_FEE_MIN = 1, XLM_FEE_MAX = 10, UPLOAD_DIVISOR = 1000, RUN_DIVISOR = 100000 }

[build]
command = "npm i && npm run build"
[build.upload]
format = "modules"
main = "./shim.mjs"